language: python
postgres:
    adapter: postgresql
    database: makahiki
    username: postgres
env:
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/makahiki MAKAHIKI_ADMIN_INFO=admin:admin
install: pip install -r requirements.txt --use-mirrors --quiet
before_script:
    - "psql -c 'create database makahiki;' -U postgres"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"  
script: coverage run --source=makahiki/apps/ makahiki/manage.py test
after_script:
    - coverage report -m
    - cd makahiki;
    - scripts/run_pylint.sh
    - scripts/run_pep8.sh
notifications:
    email:
        - makahiki-dev@googlegroups.com